steps:     
  - name: gcr.io/cloud-builders/docker
    id: Build
    entrypoint: bash
    args:
    - '-c'
    - |
        docker build -t ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${_IMGV_} -t ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${SHORT_SHA} .

  - name: gcr.io/cloud-builders/docker
    id: Push
    entrypoint: bash
    args:
    - '-c'
    - |
       docker push ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${_IMGV_}
       docker push ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${SHORT_SHA}
       
substitutions:
  _REGISTRY_: us-central1-docker.pkg.dev/test-cloudbuild-8712/demo-registry
  _APPNAME_: simplepythonapp
  _ENV_: dev
  _PYTHON_VERSION: latest
  _IMGV_: latest
