steps:     
  - name: gcr.io/cloud-builders/docker
    id: Build
    entrypoint: bash
    args:
    - '-c'
    - |
        docker build -t ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${_IMGV_} -t ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${SHORT_SHA} .

  - name: gcr.io/cloud-builders/docker
    id: Push
    entrypoint: bash
    args:
    - '-c'
    - |
       docker push ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${_IMGV_}
       docker push ${_REGISTRY_}/${_APPNAME_}:${_ENV_}-${SHORT_SHA}
       
       
  # Access the id_github file from Secret Manager
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=github > /root/.ssh/id_github' ]
    volumes:
    - name: 'ssh'
      path: /root/.ssh
      
  # Set up git with key and domain
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      chmod 600 /root/.ssh/id_github
      cat <<EOF >/root/.ssh/config
      Hostname github.com
      IdentityFile /root/.ssh/id_github
      EOF
      ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    volumes:
    - name: 'ssh'
      path: /root/.ssh
       
  # Edit Kustomize layer in config repo and push changes
  - name: gcr.io/cloud-builders/git
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      echo "Cloning repo ..."
      git config --global user.name hbangaruu
      git config --global user.email hkbangaru@gmail.com
      git clone --depth 1 git@github.com:hbangaruu/Demo-App.git
      echo "Updating image tag version ..."
      cd Demo-App
      ls
      sed -i "s|tag: .*|tag: $SHORT_SHA|" Charts/sample-flask-app/values.yaml
      echo "Pushing changes to git config repo ..."
      git add -A
      git commit -m "Updated with build ${BUILD_ID} from ${REPO_NAME} commit ${COMMIT_SHA}"
      git push origin master
      
substitutions:
  _REGISTRY_: us-central1-docker.pkg.dev/test-cloudbuild-8712/demo-registry
  _APPNAME_: simplepythonapp
  _ENV_: dev
  _PYTHON_VERSION: latest
  _IMGV_: latest
